services:
  bot:
    build: ./TgBot
    restart: always
    depends_on: [downloadapi, sendingapi, dbapi]
    environment:
      - BOT_TOKEN=6338019607:AAG59LrJuKePOlGgepikMt86h14riUZ-vPA
      - DOWNLOAD_API_BASE_URL=http://127.0.0.1:8001
      - SEND_API_BASE_URL=http://127.0.0.1:8002
      - DATABASE_API_BASE_URL=http://127.0.0.1:8000
    networks: [internal]

  dbapi:
    build: ./DataBaseAPI
    restart: always
    networks: [internal]
    expose:
      - "8000"

  downloadapi:
    build: ./DownloadAPI
    restart: always
    networks: [internal]
    expose:
      - "8001"

  sendingapi:
    build: ./SendingAPI
    restart: always
    depends_on: [dbapi]
    environment:
      - BOT_TOKEN=6338019607:AAG59LrJuKePOlGgepikMt86h14riUZ-vPA
      - DATABASE_API_BASE_URL=http://127.0.0.1:8000
    networks: [internal]
    expose:
      - "8002"

networks:
  internal:
    driver: bridge
